use crate::error::WalError;
use serde::{Deserialize, Serialize};
use std::collections::VecDeque;

const WARNING: &str =
    "# Do not edit or delete this file\n# This file is auto-generated by the walcraft library\n";

// todo: update meta information when new files are created
// sync this information to disk
// Disk sync shall happen when a new file is create and upon close on filled
// current_pointer can be used for this
#[derive(Serialize, Deserialize)]
pub(crate) struct Meta {
    gc_pointer: u32,
    current_pointer: u32,
    pub(crate) segments: VecDeque<SizeEntry>,
}

impl Default for Meta {
    fn default() -> Self {
        Self {
            gc_pointer: 0,
            current_pointer: 1,
            segments: VecDeque::new(),
        }
    }
}

#[derive(Serialize, Deserialize)]
pub(crate) struct SizeEntry {
    pub(crate) file_id: u32,
    pub(crate) page_size: usize, // todo: delete this field if unused
    pub(crate) file_size: usize,
}

impl Meta {
    pub fn read_from_file<P: AsRef<std::path::Path>>(path: P) -> Result<Self, WalError> {
        let contents = std::fs::read_to_string(path)
            .map_err(|e| WalError::IoError(format!("Failed to read metadata: {}", e)))?;
        toml::from_str(&contents)
            .map_err(|e| WalError::IoError(format!("Failed to deserialize metadata: {}", e)))
    }

    pub fn write_to_file<P: AsRef<std::path::Path>>(&self, path: P) -> Result<(), WalError> {
        let contents = toml::to_string(self)
            .map_err(|e| WalError::IoError(format!("Failed to serialize metadata: {}", e)))?;
        let contents = format!("{}{}", WARNING, contents);
        std::fs::write(path, contents)
            .map_err(|e| WalError::IoError(format!("Failed to write metadata to IO {}", e)))?;
        Ok(())
    }
}

#[test]
fn it_works() {
    // file path
    let mut path = std::path::PathBuf::from(crate::TESTING_DIR);
    path.push("meta_test.toml");
    // create a new file
    let meta = Meta {
        gc_pointer: 0,
        current_pointer: 101,
        segments: VecDeque::from([
            SizeEntry {
                file_id: 1,
                page_size: 4096,
                file_size: 8192,
            },
            SizeEntry {
                file_id: 2,
                page_size: 1024,
                file_size: 2048,
            },
        ]),
    };
    meta.write_to_file(&path).unwrap();
    // read from file
    let meta = Meta::read_from_file(path).unwrap();
    assert_eq!(meta.gc_pointer, 0);
    assert_eq!(meta.current_pointer, 101);
    assert_eq!(meta.segments.len(), 2);
    assert_eq!(meta.segments[1].page_size, 1024);
    assert_eq!(meta.segments[1].file_size, 2048);
}
