use crate::error::WalError;
use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use std::path::{Path, PathBuf};

const WARNING: &str =
    "# Do not edit or delete this file\n# This file is auto-generated by the walcraft library\n";

// todo: update meta information when new files are created
// sync this information to disk
// Disk sync shall happen when a new file is create and upon close on filled
// current_pointer can be used for this
#[derive(Serialize, Deserialize)]
pub(crate) struct Meta {
    #[serde(skip)]
    pub(crate) dirty: bool,
    #[serde(skip)]
    location: PathBuf,
    pub(crate) init: bool,
    pub(crate) current_pointer: u32,
    pub(crate) segments: VecDeque<SizeEntry>,
}

impl Meta {
    pub(crate) fn new<P: AsRef<Path>>(path: P) -> Self {
        let path = Self::path(path);
        Self {
            dirty: true,
            init: false,
            location: path,
            current_pointer: 0,
            segments: VecDeque::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub(crate) struct SizeEntry {
    pub(crate) file_id: u32,
    pub(crate) page_size: usize, // todo: delete this field if unused
    pub(crate) file_size: usize,
}

impl Meta {
    pub fn read_from_file<P: AsRef<Path>>(base_dir: P) -> Result<Self, WalError> {
        let path = Self::path(base_dir);
        let contents = std::fs::read_to_string(&path)
            .map_err(|e| WalError::IoError(format!("Failed to read metadata: {}", e)))?;
        let mut meta: Meta = toml::from_str(&contents)
            .map_err(|e| WalError::IoError(format!("Failed to deserialize metadata: {}", e)))?;
        meta.location = path;
        Ok(meta)
    }

    pub fn sync(&mut self) -> Result<(), WalError> {
        if !self.dirty {
            return Ok(());
        }
        let contents = toml::to_string(self)
            .map_err(|e| WalError::IoError(format!("Failed to serialize metadata: {}", e)))?;
        let contents = format!("{}{}", WARNING, contents);
        std::fs::write(&self.location, contents)
            .map_err(|e| WalError::IoError(format!("Failed to write metadata to IO: {}", e)))?;
        self.dirty = false;
        Ok(())
    }

    pub fn path<P: AsRef<Path>>(base_dir: P) -> PathBuf {
        let mut path = PathBuf::from(base_dir.as_ref());
        path.push("meta.toml");
        path
    }
}

#[test]
fn it_works() {
    let path = crate::TESTING_DIR;
    // create a new file
    let mut meta = Meta {
        dirty: true,
        init: true,
        location: Meta::path(path),
        current_pointer: 101,
        segments: VecDeque::from([
            SizeEntry {
                file_id: 1,
                page_size: 4096,
                file_size: 8192,
            },
            SizeEntry {
                file_id: 2,
                page_size: 1024,
                file_size: 2048,
            },
        ]),
    };
    meta.sync().unwrap();
    // read from the file
    let meta = Meta::read_from_file(path).unwrap();
    assert_eq!(meta.current_pointer, 101);
    assert_eq!(meta.segments.len(), 2);
    assert_eq!(meta.segments[1].page_size, 1024);
    assert_eq!(meta.segments[1].file_size, 2048);
}
